#! /bin/sh

sxhkd &
feh --bg-scale Pictures/Wallpaper3.png
picom -b
killall tty-clock

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config normal_border_color  '#C43323'
bspc config focused_border_color '#FC7442'
bspc config top_padding 	10
bspc config bottom_padding 	10
bspc config left_padding 	10
bspc config right_padding 	10

bspc config honor_size_hints	true

bspc config window_gap          10

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

bspc config ignore_ewmh_focus 		false

bspc rule -a kitty state=floating rectangle=580x340+300+200

#spent two days writing a bash script to do what the next two lines do -_-
bspc rule -a '*:*' -o state=floating rectangle=300x160+20+20; \
kitty -e tty-clock -C 1 -c -f '%A, %B %d, %Y' 

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a 'Zathura' follow=on state=tiled
